"""
POISuggestion model for AI-generated points of interest.
"""

from datetime import datetime
from typing import Optional
from uuid import UUID, uuid4

from sqlalchemy import String, Text, DateTime, ForeignKey, Numeric
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class POISuggestion(Base):
    """
    A point of interest suggestion generated by AI.
    
    These are never automatically canonical. Authors must
    explicitly accept them to become part of the world.
    """
    
    __tablename__ = "poi_suggestions"
    
    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)
    world_id: Mapped[UUID] = mapped_column(
        ForeignKey("worlds.id", ondelete="CASCADE"), 
        nullable=False
    )
    location_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("locations.id"), 
        default=None
    )
    poi_type: Mapped[Optional[str]] = mapped_column(String(100), default=None)
    description: Mapped[Optional[str]] = mapped_column(Text, default=None)
    source_chapter_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("chapters.id"), 
        default=None
    )
    confidence: Mapped[float] = mapped_column(Numeric(3, 2), default=0.5)
    status: Mapped[str] = mapped_column(String(50), default="pending")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), 
        default=datetime.utcnow
    )
    
    # Relationships
    world = relationship("World", back_populates="poi_suggestions")
    location = relationship("Location")
    source_chapter = relationship("Chapter")
    
    def __repr__(self) -> str:
        return f"<POISuggestion(id={self.id}, type='{self.poi_type}', status={self.status})>"
